packages:
  - packages/**

catalog:
  "@antfu/eslint-config": ^4.12.0
  "@types/vscode": ^1.99.1
  "@volar/language-server": ^2.4.12
  "@volar/vscode": ^2.4.12
  "@zinkawaii/eslint-config": ^0.2.3
  "@zinkawaii/scripts": ^0.0.1
  "@zinkawaii/tsconfig": ^0.0.1
  bumpp: ^10.1.0
  eslint: ^9.25.1
  reactive-vscode: ^0.2.14
  rolldown: 1.0.0-beta.8
  tsdown: ^0.9.6
  vitest: ^3.1.2
  vscode-uri: ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver